# Databricks notebook source
# MAGIC %md
# MAGIC # Creating the lakehouse catalog
# MAGIC
# MAGIC ## WARNING !!! the following cell drops the existing lakehouse layers

# COMMAND ----------

# MAGIC %sql
# MAGIC USE CATALOG jeromeattinger_lakehouse;
# MAGIC
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## Create tables in Gold

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC -- Create a managed table in our Unity Catalog
# MAGIC CREATE OR REPLACE TABLE gold.dim_calendar AS
# MAGIC -- CTE to simplify our SQL
# MAGIC WITH calendar_dates AS (
# MAGIC     SELECT
# MAGIC         explode(array_dates) AS calendar_date
# MAGIC     FROM (
# MAGIC         SELECT
# MAGIC             SEQUENCE(
# MAGIC                 MAKE_DATE(2000, 01, 01), -- Start date
# MAGIC                 MAKE_DATE(2030, 01, 01), -- End date
# MAGIC                 INTERVAL 1 DAY           -- Incremental step
# MAGIC             ) AS array_dates
# MAGIC     )
# MAGIC )
# MAGIC -- The SQL transforming our main calendar_date into all the columns we will be requiring
# MAGIC SELECT
# MAGIC     -- Calendar table primary key
# MAGIC     10000 * YEAR(calendar_date) + 100 * MONTH(calendar_date) + DAY(calendar_date) AS _tf_dim_calendar_id, 
# MAGIC
# MAGIC     TO_DATE(calendar_date) AS cal_date,
# MAGIC     YEAR(calendar_date) AS cal_year,
# MAGIC     MONTH(calendar_date) AS cal_month,
# MAGIC     DAY(calendar_date) AS calendar_day_of_month,
# MAGIC     DATE_FORMAT(calendar_date, 'EEEE MMMM dd yyyy') AS cal_date_full,
# MAGIC     DATE_FORMAT(calendar_date, 'EEEE') AS cal_day_name,
# MAGIC     CASE
# MAGIC         WHEN DATE_ADD(calendar_date, (WEEKDAY(calendar_date) + 1) - 1) = calendar_date THEN TO_DATE(calendar_date)
# MAGIC         ELSE DATE_ADD(calendar_date, -(WEEKDAY(calendar_date)))
# MAGIC     END AS cal_week_start, -- Start of week date
# MAGIC     DATE_ADD(
# MAGIC         CASE
# MAGIC             WHEN DATE_ADD(calendar_date, (WEEKDAY(calendar_date) + 1) - 1) = calendar_date THEN TO_DATE(calendar_date)
# MAGIC             ELSE DATE_ADD(calendar_date, -(WEEKDAY(calendar_date)))
# MAGIC         END,
# MAGIC         6
# MAGIC     ) AS cal_week_end, -- End of week date
# MAGIC     WEEKDAY(calendar_date) + 1 AS cal_week_day,
# MAGIC     WEEKOFYEAR(calendar_date) AS cal_week_of_year,
# MAGIC     DATE_FORMAT(calendar_date, 'MMMM yyyy') AS cal_month_year,
# MAGIC     DATE_FORMAT(calendar_date, 'MMMM') AS cal_month_name,
# MAGIC     DATE_ADD(LAST_DAY(ADD_MONTHS(calendar_date, -1)), 1) AS cal_first_day_of_month,
# MAGIC     LAST_DAY(calendar_date) AS cal_last_day_of_month,
# MAGIC     CASE
# MAGIC         WHEN MONTH(calendar_date) IN (1, 2, 3) THEN 1
# MAGIC         WHEN MONTH(calendar_date) IN (4, 5, 6) THEN 2
# MAGIC         WHEN MONTH(calendar_date) IN (7, 8, 9) THEN 3
# MAGIC         ELSE 4
# MAGIC     END AS cal_fiscal_quarter,
# MAGIC     YEAR(DATE_ADD(calendar_date, 89)) AS cal_fiscal_year,
# MAGIC
# MAGIC     -- Technical columns
# MAGIC     current_timestamp() AS _tf_create_date,
# MAGIC     current_timestamp() AS _tf_update_date
# MAGIC FROM calendar_dates;
# MAGIC
# MAGIC -- modify our calendar table in order to set a PK (primary key)
# MAGIC ALTER TABLE gold.dim_calendar
# MAGIC ALTER COLUMN _tf_dim_calendar_id SET NOT NULL;
# MAGIC
# MAGIC ALTER TABLE gold.dim_calendar ADD PRIMARY KEY (_tf_dim_calendar_id);

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE gold.dim_geography (
# MAGIC   -- Incremental surrogate key
# MAGIC   _tf_dim_geography_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
# MAGIC
# MAGIC   -- Attributes
# MAGIC   geo_address_id INT,
# MAGIC   geo_address_line_1 STRING,
# MAGIC   geo_address_line_2 STRING,
# MAGIC   geo_city STRING,
# MAGIC   geo_state_province STRING,
# MAGIC   geo_country_region STRING,
# MAGIC   geo_postal_code STRING,
# MAGIC
# MAGIC   -- Technical columns
# MAGIC   _tf_create_date TIMESTAMP,
# MAGIC   _tf_update_date TIMESTAMP
# MAGIC );

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO gold.dim_geography (
# MAGIC     _tf_dim_geography_id, 
# MAGIC     geo_address_id, 
# MAGIC     geo_address_line_1, 
# MAGIC     geo_address_line_2, 
# MAGIC     geo_city, 
# MAGIC     geo_state_province, 
# MAGIC     geo_country_region, 
# MAGIC     geo_postal_code, 
# MAGIC     _tf_create_date, 
# MAGIC     _tf_update_date)
# MAGIC
# MAGIC VALUES (-9, 0, 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', current_timestamp(), current_timestamp());

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE gold.dim_customer (
# MAGIC   -- Incremental surrogate key
# MAGIC   _tf_dim_customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
# MAGIC
# MAGIC   -- Attributes
# MAGIC   cust_customer_id INT,
# MAGIC   cust_title STRING,
# MAGIC   cust_first_name STRING,
# MAGIC   cust_middle_name STRING,
# MAGIC   cust_last_name STRING,
# MAGIC   cust_suffix STRING,
# MAGIC   cust_company_name STRING,
# MAGIC   cust_sales_person STRING,
# MAGIC   cust_email_address STRING,
# MAGIC   cust_phone STRING,
# MAGIC
# MAGIC   -- Technical columns
# MAGIC   _tf_create_date TIMESTAMP,
# MAGIC   _tf_update_date TIMESTAMP
# MAGIC );

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO gold.dim_customer (
# MAGIC   _tf_dim_customer_id,
# MAGIC   cust_customer_id,
# MAGIC   cust_title,
# MAGIC   cust_first_name,
# MAGIC   cust_middle_name,
# MAGIC   cust_last_name,
# MAGIC   cust_suffix,
# MAGIC   cust_company_name,
# MAGIC   cust_sales_person,
# MAGIC   cust_email_address,
# MAGIC   cust_phone,
# MAGIC   _tf_create_date,
# MAGIC   _tf_update_date)
# MAGIC
# MAGIC VALUES (-9, 0, 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', current_timestamp(), current_timestamp());
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE gold.fact_sales (
# MAGIC   -- Incremental surrogate key
# MAGIC   _tf_fact_sales_id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL, 
# MAGIC
# MAGIC   -- Source id
# MAGIC   sales_order_id INT,
# MAGIC   sales_order_detail_id INT,
# MAGIC
# MAGIC   -- Foreign keys to dimensions
# MAGIC   _tf_dim_calendar_id INT 
# MAGIC   REFERENCES gold.dim_calendar(_tf_dim_calendar_id),
# MAGIC   _tf_dim_customer_id BIGINT 
# MAGIC   REFERENCES gold.dim_customer(_tf_dim_customer_id),
# MAGIC   _tf_dim_geography_id BIGINT 
# MAGIC   REFERENCES gold.dim_geography(_tf_dim_geography_id),
# MAGIC   
# MAGIC   -- Measures
# MAGIC   sales_order_qty SMALLINT,
# MAGIC   sales_unit_price DECIMAL(19, 4),
# MAGIC   sales_unit_price_discount DECIMAL(19, 4),
# MAGIC   sales_line_total DECIMAL(38, 6),
# MAGIC   
# MAGIC   -- Technical columns
# MAGIC   _tf_create_date TIMESTAMP,
# MAGIC   _tf_update_date TIMESTAMP
# MAGIC );

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE gold.dim_product (
# MAGIC   -- Incremental surrogate key
# MAGIC   _tf_dim_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
# MAGIC
# MAGIC   -- Attributes
# MAGIC   prod_product_id INT,                   -- Clé naturelle issue de la source
# MAGIC   prod_name STRING,                      -- Nom du produit
# MAGIC   prod_product_number STRING,            -- Numéro de produit
# MAGIC   prod_color STRING,                     -- Couleur du produit
# MAGIC   prod_size STRING,                      -- Taille du produit
# MAGIC   prod_standard_cost DECIMAL(18, 2),     -- Coût standard
# MAGIC   prod_list_price DECIMAL(18, 2),        -- Prix de liste
# MAGIC   prod_weight DECIMAL(18, 2),            -- Poids du produit
# MAGIC   prod_model_name STRING,                -- Nom du modèle
# MAGIC   prod_category_name STRING,             -- Nom de la catégorie
# MAGIC   prod_thumbnail_photo STRING,           -- Miniature du produit
# MAGIC   prod_description STRING,               -- Description du produit
# MAGIC
# MAGIC   -- Technical columns
# MAGIC   _tf_create_date TIMESTAMP,             -- Date de création
# MAGIC   _tf_update_date TIMESTAMP              -- Date de mise à jour
# MAGIC );

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO gold.dim_product (
# MAGIC   _tf_dim_product_id,
# MAGIC   prod_product_id,
# MAGIC   prod_name,
# MAGIC   prod_product_number,
# MAGIC   prod_color,
# MAGIC   prod_size,
# MAGIC   prod_standard_cost,
# MAGIC   prod_list_price,
# MAGIC   prod_weight,
# MAGIC   prod_model_name,
# MAGIC   prod_category_name,
# MAGIC   prod_thumbnail_photo,
# MAGIC   prod_description,
# MAGIC   _tf_create_date,
# MAGIC   _tf_update_date
# MAGIC )
# MAGIC VALUES (
# MAGIC   -9, -- ID incrémental fictif
# MAGIC   0,  -- Identifiant du produit (inconnu)
# MAGIC   'N/A', -- Nom du produit
# MAGIC   'N/A', -- Numéro du produit
# MAGIC   'N/A', -- Couleur du produit
# MAGIC   'N/A', -- Taille du produit
# MAGIC   0.00, -- Coût standard
# MAGIC   0.00, -- Prix de liste
# MAGIC   0.00, -- Poids
# MAGIC   'N/A', -- Modèle
# MAGIC   'N/A', -- Catégorie
# MAGIC   'N/A', -- Miniature
# MAGIC   'N/A', -- Description
# MAGIC   current_timestamp(), -- Date de création
# MAGIC   current_timestamp()  -- Date de mise à jour
# MAGIC );
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE gold.dim_address (
# MAGIC   -- Incremental surrogate key
# MAGIC   _tf_dim_address_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
# MAGIC
# MAGIC   -- Attributes
# MAGIC   addr_address_id INT,                -- Clé naturelle issue de la source
# MAGIC   addr_line1 STRING,                  -- Ligne 1 de l'adresse
# MAGIC   addr_line2 STRING,                  -- Ligne 2 de l'adresse (optionnelle)
# MAGIC   addr_city STRING,                   -- Ville
# MAGIC   addr_state_province STRING,         -- État ou province
# MAGIC   addr_country_region STRING,         -- Pays ou région
# MAGIC   addr_postal_code STRING,            -- Code postal
# MAGIC
# MAGIC   -- Technical columns
# MAGIC   _tf_create_date TIMESTAMP,          -- Date de création
# MAGIC   _tf_update_date TIMESTAMP           -- Date de mise à jour
# MAGIC );
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO gold.dim_address (
# MAGIC   _tf_dim_address_id,
# MAGIC   addr_address_id,
# MAGIC   addr_line1,
# MAGIC   addr_line2,
# MAGIC   addr_city,
# MAGIC   addr_state_province,
# MAGIC   addr_country_region,
# MAGIC   addr_postal_code,
# MAGIC   _tf_create_date,
# MAGIC   _tf_update_date
# MAGIC )
# MAGIC VALUES (
# MAGIC   -9,              -- ID incrémental fictif
# MAGIC   0,               -- Identifiant de l'adresse (inconnu)
# MAGIC   'N/A',           -- Ligne 1 de l'adresse
# MAGIC   'N/A',           -- Ligne 2 de l'adresse
# MAGIC   'N/A',           -- Ville
# MAGIC   'N/A',           -- État ou province
# MAGIC   'N/A',           -- Pays ou région
# MAGIC   'N/A',           -- Code postal
# MAGIC   current_timestamp(), -- Date de création
# MAGIC   current_timestamp()  -- Date de mise à jour
# MAGIC );
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE gold.dim_order (
# MAGIC   -- Incremental surrogate key
# MAGIC   _tf_dim_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
# MAGIC
# MAGIC   -- Attributes
# MAGIC   order_order_id INT,                 -- Clé naturelle issue de la source
# MAGIC   order_date DATE,                    -- Date de la commande
# MAGIC   order_due_date DATE,                -- Date d'échéance
# MAGIC   order_ship_date DATE,               -- Date d'expédition
# MAGIC   order_status STRING,                -- Statut de la commande
# MAGIC   order_online_flag BOOLEAN,          -- Commande en ligne (true/false)
# MAGIC   order_ship_method STRING,           -- Méthode d'expédition
# MAGIC   order_tax_amount DECIMAL(18, 2),    -- Montant des taxes
# MAGIC   order_freight DECIMAL(18, 2),       -- Frais de transport
# MAGIC   order_subtotal DECIMAL(18, 2),      -- Sous-total
# MAGIC   order_total_due DECIMAL(18, 2),     -- Montant total
# MAGIC
# MAGIC   -- Technical columns
# MAGIC   _tf_create_date TIMESTAMP,          -- Date de création
# MAGIC   _tf_update_date TIMESTAMP           -- Date de mise à jour
# MAGIC );
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO gold.dim_order (
# MAGIC   _tf_dim_order_id,
# MAGIC   order_order_id,
# MAGIC   order_date,
# MAGIC   order_due_date,
# MAGIC   order_ship_date,
# MAGIC   order_status,
# MAGIC   order_online_flag,
# MAGIC   order_ship_method,
# MAGIC   order_tax_amount,
# MAGIC   order_freight,
# MAGIC   order_subtotal,
# MAGIC   order_total_due,
# MAGIC   _tf_create_date,
# MAGIC   _tf_update_date
# MAGIC )
# MAGIC VALUES (
# MAGIC   -9,                  -- ID incrémental fictif
# MAGIC   0,                   -- Identifiant de la commande (inconnu)
# MAGIC   NULL,                -- Date de la commande (nulle)
# MAGIC   NULL,                -- Date d'échéance (nulle)
# MAGIC   NULL,                -- Date d'expédition (nulle)
# MAGIC   'N/A',               -- Statut de la commande
# MAGIC   NULL,                -- Commande en ligne (inconnue)
# MAGIC   'N/A',               -- Méthode d'expédition
# MAGIC   0.00,                -- Montant des taxes
# MAGIC   0.00,                -- Frais de transport
# MAGIC   0.00,                -- Sous-total
# MAGIC   0.00,                -- Montant total
# MAGIC   current_timestamp(), -- Date de création
# MAGIC   current_timestamp()  -- Date de mise à jour
# MAGIC );
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE gold.fact_sales_detail (
# MAGIC   -- Incremental surrogate key
# MAGIC   _tf_fact_sales_detail_id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
# MAGIC
# MAGIC   -- Source ids
# MAGIC   sales_order_id INT,
# MAGIC   sales_order_detail_id INT,
# MAGIC
# MAGIC   -- Foreign keys to dimensions
# MAGIC   _tf_dim_order_id BIGINT 
# MAGIC   REFERENCES gold.dim_order(_tf_dim_order_id),
# MAGIC   _tf_dim_product_id BIGINT 
# MAGIC   REFERENCES gold.dim_product(_tf_dim_product_id),
# MAGIC   _tf_dim_customer_id BIGINT 
# MAGIC   REFERENCES gold.dim_customer(_tf_dim_customer_id),
# MAGIC   _tf_dim_calendar_id INT 
# MAGIC   REFERENCES gold.dim_calendar(_tf_dim_calendar_id),
# MAGIC   _tf_dim_geography_id BIGINT 
# MAGIC   REFERENCES gold.dim_geography(_tf_dim_geography_id),
# MAGIC
# MAGIC   -- Measures
# MAGIC   sales_order_qty SMALLINT,
# MAGIC   sales_unit_price DECIMAL(19, 4),
# MAGIC   sales_unit_price_discount DECIMAL(19, 4),
# MAGIC   sales_line_total DECIMAL(38, 6),
# MAGIC
# MAGIC   -- Technical columns
# MAGIC   _tf_create_date TIMESTAMP,
# MAGIC   _tf_update_date TIMESTAMP
# MAGIC );
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE gold.fact_shipping (
# MAGIC   -- Incremental surrogate key
# MAGIC   _tf_fact_shipping_id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
# MAGIC
# MAGIC   -- Source ids
# MAGIC   sales_order_id INT,
# MAGIC
# MAGIC   -- Foreign keys to dimensions
# MAGIC   _tf_dim_order_id BIGINT 
# MAGIC   REFERENCES gold.dim_order(_tf_dim_order_id),
# MAGIC   _tf_dim_address_id BIGINT 
# MAGIC   REFERENCES gold.dim_address(_tf_dim_address_id),
# MAGIC   _tf_dim_calendar_id INT 
# MAGIC   REFERENCES gold.dim_calendar(_tf_dim_calendar_id),
# MAGIC
# MAGIC   -- Measures
# MAGIC   shipping_freight DECIMAL(19, 4),         -- Frais de transport
# MAGIC   shipping_tax_amount DECIMAL(19, 4),      -- Taxes sur le transport
# MAGIC   shipping_total DECIMAL(19, 4),           -- Total du transport (freight + taxes)
# MAGIC   shipping_duration_days INT,              -- Durée d'expédition en jours (ShipDate - OrderDate)
# MAGIC
# MAGIC   -- Technical columns
# MAGIC   _tf_create_date TIMESTAMP,
# MAGIC   _tf_update_date TIMESTAMP
# MAGIC );
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE gold.fact_product (
# MAGIC   -- Incremental surrogate key
# MAGIC   _tf_fact_product_id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
# MAGIC   
# MAGIC   -- Source ids
# MAGIC   product_id INT,
# MAGIC
# MAGIC   -- Foreign keys to dimensions
# MAGIC   _tf_dim_product_id BIGINT 
# MAGIC   REFERENCES gold.dim_product(_tf_dim_product_id),
# MAGIC   _tf_dim_calendar_id INT 
# MAGIC   REFERENCES gold.dim_calendar(_tf_dim_calendar_id),
# MAGIC
# MAGIC   -- Measures
# MAGIC   product_standard_cost DECIMAL(19, 4),    -- Coût standard du produit
# MAGIC   product_list_price DECIMAL(19, 4),      -- Prix de liste du produit
# MAGIC   product_weight DECIMAL(19, 4),          -- Poids du produit
# MAGIC   product_inventory_quantity INT,         -- Quantité en stock
# MAGIC   product_discontinued BOOLEAN,           -- Produit discontinué (true/false)
# MAGIC
# MAGIC   -- Technical columns
# MAGIC   _tf_create_date TIMESTAMP,
# MAGIC   _tf_update_date TIMESTAMP
# MAGIC );
# MAGIC
